{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-plugin",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-plugin-1.0.8.jar",
          "url": "lancet-plugin-1.0.8.jar",
          "size": 59172,
          "sha512": "1e4257120a28af7d9565dd0ea005d1e4193dd46c1bc778bb4b41dae4502fc9c7c8b0382da98588a4dfc898c9ead317a3e5523a24a234ff0ae71d046a46ec9f0f",
          "sha256": "51dbb59a5163d5c6ee498277dff31327b887bdcdc7e6dd63511d5cb90f7b78a0",
          "sha1": "7ec008afe9de4d211c367b5963c6a508b0462c6c",
          "md5": "a3bb63bac8900ff843de384ec7283895"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-weaver",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-1.0.8.jar",
          "url": "lancet-plugin-1.0.8.jar",
          "size": 59172,
          "sha512": "1e4257120a28af7d9565dd0ea005d1e4193dd46c1bc778bb4b41dae4502fc9c7c8b0382da98588a4dfc898c9ead317a3e5523a24a234ff0ae71d046a46ec9f0f",
          "sha256": "51dbb59a5163d5c6ee498277dff31327b887bdcdc7e6dd63511d5cb90f7b78a0",
          "sha1": "7ec008afe9de4d211c367b5963c6a508b0462c6c",
          "md5": "a3bb63bac8900ff843de384ec7283895"
        }
      ]
    }
  ]
}
