{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-weaver",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-weaver-1.0.9.jar",
          "url": "lancet-weaver-1.0.9.jar",
          "size": 127866,
          "sha512": "dd89bbded9fe92845199abb8e0e80f75d7f78bb071e6b4e6713cd11945f3b2c88043cc96741a41758a6610ad2a0fdf3ea63cc2736198b4edead47556eb0c5c6e",
          "sha256": "56534430789ed86b9f95bf184d4b7d00af5905f18e0793702603a64f59d1d136",
          "sha1": "c9786af2d0b261a481fefa6d1a962063fabe952b",
          "md5": "394ac1a160e0d34c14790617d2cc1dfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-weaver-1.0.9.jar",
          "url": "lancet-weaver-1.0.9.jar",
          "size": 127866,
          "sha512": "dd89bbded9fe92845199abb8e0e80f75d7f78bb071e6b4e6713cd11945f3b2c88043cc96741a41758a6610ad2a0fdf3ea63cc2736198b4edead47556eb0c5c6e",
          "sha256": "56534430789ed86b9f95bf184d4b7d00af5905f18e0793702603a64f59d1d136",
          "sha1": "c9786af2d0b261a481fefa6d1a962063fabe952b",
          "md5": "394ac1a160e0d34c14790617d2cc1dfa"
        }
      ]
    }
  ]
}
