{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-weaver",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-weaver-1.0.8.jar",
          "url": "lancet-weaver-1.0.8.jar",
          "size": 127879,
          "sha512": "6651e8a5be9c85d826382ef5b21784ae7bee5255de9746d28867bb3a4db0025f30d699c1c5209ebed58819dc0ee12e1a78e7f1326a7623d6c1d6bc7f4eaf4ed8",
          "sha256": "6d4320e1ed3b751f71dcfa0a78ffec70141e7d9cba928f9ffc02967342e4357b",
          "sha1": "3bdcd44b7f7ffdda42e68626a7ee79f0dc3a0683",
          "md5": "d0b7203578d32f41e3986ef1d44be323"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-weaver-1.0.8.jar",
          "url": "lancet-weaver-1.0.8.jar",
          "size": 127879,
          "sha512": "6651e8a5be9c85d826382ef5b21784ae7bee5255de9746d28867bb3a4db0025f30d699c1c5209ebed58819dc0ee12e1a78e7f1326a7623d6c1d6bc7f4eaf4ed8",
          "sha256": "6d4320e1ed3b751f71dcfa0a78ffec70141e7d9cba928f9ffc02967342e4357b",
          "sha1": "3bdcd44b7f7ffdda42e68626a7ee79f0dc3a0683",
          "md5": "d0b7203578d32f41e3986ef1d44be323"
        }
      ]
    }
  ]
}
